### ISSUE TITLE
angular2-rc3 is out last week - no support

### ISSUE THREAD

**Issue by nasreddineskandrani** [rangle/rangle-starter#133] opened 2016-06-24 12:44 UTC
when you will upgrade to rc3 support please?

**Comment by SethDavenport** [comment] 2016-06-24 17:44
Duplicate of #132

**Closed as completed** 2016-06-24 17:47 UTC

**Comment by SethDavenport** [comment] 2016-06-24 18:01
We're still evaluating the router situation - there's no router-deprecated in RC3, but the v2 and v3 routers are still experimental.

**Comment by SethDavenport** [comment] 2016-06-26 02:29
angular2-starter and angular2-redux-starter have been updated to RC3.
