### ISSUE TITLE
Update circle.yml to use built in yarn

### ISSUE THREAD

**Issue by bennett000** [rangle/rangle-starter#208] opened 2016-12-06 22:48 UTC
Current `circle.yml` files `npm install -g yarn` but there are official instructions.  This typically save ~20-30 seconds on builds: https://circleci.com/docs/install-and-use-yarn/

**Comment by SethDavenport** [comment] 2016-12-06 22:51
w00t - this was not available from circle when I started

**Comment by bennett000** [comment] 2016-12-06 23:15
Yeah even in its current state it's got messy output and is kind of patchy, but I'm glad they did it because it really helped on another project.

We also figured out how to do the AoT build in parallel with the test run which helps reduce the time too.  That would be another card and I wanted to ask you about it first.

**Comment by SethDavenport** [comment] 2017-01-13 22:08
This is a dupe of #221

**Closed as completed** 2017-01-13 22:09 UTC
