### ISSUE TITLE
Got couple of critical dependency warning while running during development in angular2-starter 

### ISSUE THREAD

**Issue by sivaramsi** [rangle/rangle-starter#175] opened 2016-10-05 11:01 UTC
client?cd17:69 ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
45:15 Critical dependency: the request of a dependency is an expression
CriticalDependencyWarning: Critical dependency: the request of a dependency is an expression
    at SystemImportContextDependency.getWarnings (F:\angular 2\angular2-starter\node_modules\webpack\lib\dependencies\SystemImportContextDependency.js:23:4)
    at F:\angular 2\angular2-starter\node_modules\webpack\lib\Compilation.js:645:21
    at Array.forEach (native)
    at F:\angular 2\angular2-starter\node_modules\webpack\lib\Compilation.js:644:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (F:\angular 2\angular2-starter\node_modules\webpack\lib\Compilation.js:643:9)
    at Compilation.<anonymous> (F:\angular 2\angular2-starter\node_modules\webpack\lib\Compilation.js:505:8)
    at Array.forEach (native)
    at Compilation.finish (F:\angular 2\angular2-starter\node_modules\webpack\lib\Compilation.js:504:15)
    at Compiler.<anonymous> (F:\angular 2\angular2-starter\node_modules\webpack\lib\Compiler.js:466:16)
    at F:\angular 2\angular2-starter\node_modules\tapable\lib\Tapable.js:152:11
    at Compilation.<anonymous> (F:\angular 2\angular2-starter\node_modules\webpack\lib\Compilation.js:452:10)
    at F:\angular 2\angular2-starter\node_modules\webpack\lib\Compilation.js:423:12
    at F:\angular 2\angular2-starter\node_modules\webpack\lib\Compilation.js:335:10
    at F:\angular 2\angular2-starter\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at done (F:\angular 2\angular2-starter\node_modules\webpack\node_modules\async\lib\async.js:246:17)
    at F:\angular 2\angular2-starter\node_modules\webpack\node_modules\async\lib\async.js:44:16
    at F:\angular 2\angular2-starter\node_modules\webpack\lib\Compilation.js:335:10
    at F:\angular 2\angular2-starter\node_modules\webpack\node_modules\async\lib\async.js:52:16
    at done (F:\angular 2\angular2-starter\node_modules\webpack\node_modules\async\lib\async.js:246:17)
    at F:\angular 2\angular2-starter\node_modules\webpack\node_modules\async\lib\async.js:44:16
    at F:\angular 2\angular2-starter\node_modules\webpack\lib\Compilation.js:335:10

**Comment by rbrander** [comment] 2017-04-10 16:35
@sivaramsi I'm unable to reproduce this.  There have been lots of changes to Angular since Oct 5, 2016 (when you created this issue).  I'm hoping that you no longer have this issue.

I'm going to close this issue and if you're still having issues, please open a new issue.

**Closed as completed by rbrander** 2017-04-10 16:35 UTC
