### ISSUE TITLE
has problem 

### ISSUE THREAD

**Issue by helojo** [rangle/rangle-starter#216] opened 2017-01-23 08:35 UTC
ERROR in [default] E:/workspace/typescript/typescript-react-redux-example/src/store/configure-store.ts:11:18
Cannot find module 'redux-thunk'.

ERROR in [default] E:/workspace/typescript/typescript-react-redux-example/src/store/configure-store.ts:13:21
Cannot find name 'require'.

ERROR in [default] E:/workspace/typescript/typescript-react-redux-example/src/store/configure-store.ts:57:18
Cannot find name 'module'.

ERROR in [default] E:/workspace/typescript/typescript-react-redux-example/src/store/configure-store.ts:60:30
Cannot find name 'require'.

ERROR in [default] E:/workspace/typescript/typescript-react-redux-example/src/store/logger.ts:1:21
Cannot find name 'require'.

ERROR in [default] E:/workspace/typescript/typescript-react-redux-example/src/store/routes.tsx:1:23
Cannot find module 'react'.

ERROR in [default] E:/workspace/typescript/typescript-react-redux-example/src/store/routes.tsx:2:30
Cannot find name 'require'.
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 389 bytes [rendered]
        [0] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 389 bytes {0} [built]

**Comment by SethDavenport** [comment] 2017-01-27 21:58
I an unable to reproduce this. Can you provide more detail?

At first glance it looks like you are missing your typings files.  Try running `npm run typings`

**Comment by rbrander** [comment] 2017-04-07 16:24
@helojo Since this issue has had little activity since you opened it, I'm going to assume Seth's advice helped you and thus I'm closing this issue.  If you feel this issue is still relevant, please feel free to reopen it with additional steps to reproduce the error. Thanks!

**Closed as completed by rbrander** 2017-04-07 16:24 UTC
